apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      # port for outside world
      port: 80
      # port of pod
      targetPort: 8080
